[package]
name = "article-date-extractor"
version = "0.1.0"
authors = ["Alexey Zabelin <zabelin.alex@gmail.com>"]

[dependencies]
regex = "0.2"
lazy_static = "0.2.2"
chrono = "0.3"
select = { git = "https://github.com/utkarshkukreti/select.rs" }
rustc-serialize = "0.3"
error-chain = "0.10.0"
